spring:
  application:
    name: batch

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: ${job.name:none}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      register-mbeans: true