spring:
  application:
    name: batch

  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver