spring:
  application:
    name: batch

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/million_performance?rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/ten_thousand_challenges?rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      register-mbeans: true